[project]
name = "paperjson"
version = "0.1.0"
description = "Paper-thin JSON serialization/deserialization for Python dataclasses"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.11.14,<0.12"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
paperjson = { workspace = true }

[dependency-groups]
dev = [
    "paperjson",
]
